version: '3.9'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client
    image: giogiunta2606/se2-05-thesis-management:client-tag
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes: 
      - ./server:/server
    image: giogiunta2606/se2-05-thesis-management:server-tag
    ports:
      - "3001:3001"