version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    depends_on:
      - client
