###     PROPOSALS
POST http://localhost:3001/api/proposals HTTP/1.1
content-type: application/json

{
    "title": "Prank proposal",
    "type":"A prank that inspires",
    "description": "This is a fake proposal.",
    "level": "MSc",
    "expiration_date": "2023-12-22",
    "notes": "No additional notes",
    "required_knowledge": "Student must know the principle of software development.",
    "cod_degree": ["2", 3, 4],
    "cod_group": "1",
    "supervisors_obj": {
        "supervisor_id": 10000,
        "co_supervisors": [
            10001
            ],
        "external":[
            {
                "name":"Franco",
                "surname":"Solo",
                "email":"franco.solo@devops.com"
            },
            {"name": "Antonio", "surname":"Vito", "email":"vitoantonio@gmail.com"}
        ]
    },
    "keywords": [
        "AI", "Mobie", "Web dev"
    ]
}
         
         #"external_supervisor_id": ""
###

DELETE http://localhost:3001/api/proposals/33 HTTP/1.1

###
PUT http://localhost:3001/api/proposals/27 HTTP/1.1
###

GET http://localhost:3001/api/proposals HTTP/1.1
###


GET http://localhost:3001/api/proposals?cod_degree=2 HTTP/1.1

###

GET http://localhost:3001/api/proposals/teachers/10000 HTTP/1.1

###

GET http://localhost:3001/api/proposals/31 HTTP/1.1

###

PUT http://localhost:3001/api/proposals/27 HTTP/1.1
content-type: application/json

{
    "title": "Prank proposal",
    "type":"A prank that inspires",
    "description": "This is a fake proposal.",
    "level": "MSc",
    "expiration_date": "2023-12-22",
    "notes": "additional notes",
    "required_knowledge": "Student must know the principle of software development.",
    "cod_degree": ["5"],
    "cod_group": "1",
    "supervisors_obj": {
        "supervisor_id": 10000,
        "co_supervisors": [
            10001,
            10002
            ]
    },
    "keywords": [
        "AI", "Application", "Web development"
    ]
}


###     DEGREES
GET http://localhost:3001/api/degrees HTTP/1.1


###     GROUPS 
GET http://localhost:3001/api/groups HTTP/1.1


###     TEACHERS
GET http://localhost:3001/api/teachers HTTP/1.1

###
GET http://localhost:3001/api/teachers/10000 HTTP/1.1


###     STUDENTS
GET http://localhost:3001/api/students/318082 HTTP/1.1


###     KEYWORDS
GET http://localhost:3001/api/keywords HTTP/1.1


###     APPLICATIONS
GET http://localhost:3001/api/applications/proposal/15 HTTP/1.1

###

GET http://localhost:3001/api/applications/ HTTP/1.1

###

PUT http://localhost:3001/api/applications/5 HTTP/1.1
Content-Type: application/json

{
    "status": "accepted"
}


###     LEVELS
GET http://localhost:3001/api/levels HTTP/1.1
